export const buttonTextConstants = {
  CONFIRM: 'Confirm',
  CANCEL: 'Cancel',
  FILE: 'File',
  YES: 'Yes',
  NO: 'No',
  COPY: 'Copy',
  CONNECT: 'Connect',
  START_GAME: 'Start game',
  START_NEW_GAME: 'Start new game',
  CANCEL_GAME: 'Cancel game',
  RESET_ROUND: 'Reset round',
  NEXT_ISSUE: 'Next issue',
  EXIT: 'Exit',
};
